//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import runtime "k8s.io/apimachinery/pkg/runtime"

// DeepCopyInto copies all properties of this object into another Input object.
func (in *Input) DeepCopyInto(out *Input) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Github = in.Github
	out.Azure = in.Azure
	in.Tenant.DeepCopyInto(&out.Tenant)
	out.NextInsight = in.NextInsight
}

// DeepCopy creates a deep copy of Input.
func (in *Input) DeepCopy() *Input {
	if in == nil {
		return nil
	}
	out := new(Input)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *Input) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another NextInsightInput object.
func (in *NextInsightInput) DeepCopyInto(out *NextInsightInput) {
	*out = *in
}

// DeepCopy creates a deep copy of NextInsightInput.
func (in *NextInsightInput) DeepCopy() *NextInsightInput {
	if in == nil {
		return nil
	}
	out := new(NextInsightInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of this object into another TenantInput object.
func (in *TenantInput) DeepCopyInto(out *TenantInput) {
	*out = *in
	if in.Bindings != nil {
		in, out := &in.Bindings, &out.Bindings
		*out = make([]BindingInput, len(*in))
		copy(*out, *in)
	}
}
