//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import runtime "k8s.io/apimachinery/pkg/runtime"

// DeepCopyInto copies all properties of this object into another Input object.
func (in *Input) DeepCopyInto(out *Input) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.DNS = in.DNS
	if in.DNS.CredentialsSecretRef != nil {
		ref := *in.DNS.CredentialsSecretRef
		out.DNS.CredentialsSecretRef = &ref
	}
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]ClusterInput, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of Input.
func (in *Input) DeepCopy() *Input {
	if in == nil {
		return nil
	}
	out := new(Input)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *Input) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
